### PR TITLE
Fixes SDL blocking same dimension window resize events. Fixes softwar…

### PR DESCRIPTION
**Pull request by Dyrewulfe**
…e rendering blackscreen/freezing.

### CODE REVIEW

**Comment by a1studmuffin** [comment]
Hmm I just tried this out and it doesn't seem to change the behaviour on my device (HTC One M8, Android 7.1). Maybe I'm doing the wrong steps? 

Here's what I'm seeing:
- clean install + run app
- enable software renderer, save + quit
- launch app + proceed to main menu
- rotate device 90 degrees, observe black screen (menu sounds can be heard when swiping so the game is still running)
- force quit the app + relaunch + proceed to main menu
- lock + unlock screen, observe black screen again
- force quit the app + relaunch + proceed to main menu
- switch app focus to another app, then switch back to game, observe black screen again

Is that the same as you're seeing?

**Comment by Dyrewulfe** [comment]
Okay, apparently some other change I made prior to setting up my Git repo was an important part, and I overlooked it. Upon rebuilding, this is now exactly the kind of behavior I'm getting.

**Comment by Dyrewulfe** [comment]
I overlooked this part. My apologies, apparently I failed to test properly after I switched over to Git. With both of these changes in place, behavior should be as I mentioned in #2.

**Comment by Dyrewulfe** [comment]
It's worth noting that if I hadn't overlooked removing that code from my local directory copy of SDL_androidevents.c (had no version control set up, so I was removing changes that didn't work), well... Let us just say that oversight was provident.

**Comment by a1studmuffin** [comment]
Just tried out the second fix. I'm seeing it working some of the time now in certain cases - definite progress - though it still seems to break some of the time. 

Summary of steps + what I saw:
- clean install + run app, enable software renderer, save + quit
- launch app in portrait orientation + proceed to main menu, observe renderer is working with directional input as expected
- rotate device 90 degrees, observe black screen (menu sounds can be heard when swiping so the game is still running)... I was never able to find a case where rotating the device worked (except if you rotate a full 180 degrees, in which case it doesn't trigger a window resize event)
- force quit the app + relaunch in portrait orientation + proceed to main menu
- lock + unlock screen, observe main menu is visible but the renderer is broken
- force quit the app + relaunch in portrait orientation + proceed to main menu
- switch app focus to another app, then switch back to game, observe renderer is still working! definite progress
- now lock + unlock screen, and observe renderer is still working after this! interesting...
- now rotate 90 degrees, observe black screen (until restart)

So this is a definite improvement, though it seems there's still some logic that's missing. I found it interesting that after I switched app focus and came back to the game, that locking + unlocking the screen started working. Perhaps there's another local change that didn't come across in the GitHub transfer?

**Comment by Dyrewulfe** [comment]
> I found it interesting that after I switched app focus and came back to the game, that locking + unlocking the screen started working. Perhaps there's another local change that didn't come across in the GitHub transfer?

I haven't managed to get a fix on that yet. And, yeah, it's definitely odd. I suspect in this case, the gl context is lost, and for some reason, the framebuffer texture is not properly restored(maybe locking the screen doesn't properly trigger a backup?)

As for rotation, looks like we're getting slightly different results(hooray for Android fragmentation!). In my case, switching out and then back in after a rotation restores the screen(rotate cdda->home screen->back to cdda).

This does currently allow a player to use software rendering reliably, as long as the orientation is locked and they're aware of the lockscreen issue, though. Having to restart the game every time the app is paused was a deal-breaker for me.

**Comment by a1studmuffin** [comment]
Yeah this is a definite improvement - it would be great if we could get a fix for the lockscreen issue though as I imagine that's going to come up a lot.

That said, I'm happy to accept this PR unless you want to keep looking at the lockscreen and/or rotation issue? 

It'll probably make sense once this is in for me to lock the orientation to landscape and enable the software renderer by default.

**Comment by Dyrewulfe** [comment]
> It'll probably make sense once this is in for me to lock the orientation to landscape

Mentioned this over in #2 (I wish I'd had the presence of mind to just keep the convo here...), but this might be a bad idea. As long as we avoid live rotation, there's no issue. And options are nice to have.

I'm going to take another stab at solving the screen lock issue today. But if I can't get it licked in the next 12 hours or so, might as well merge this for now. I can always make another PR when I figure it out. And I'm planning to transition to a fully command line driven development environment this evening. Setting it all up will probably use up my dev time for a day or three.

**Comment by Dyrewulfe** [comment]
Found it. Commit's incoming, just need to clean up my work and run tests.

**Comment by Dyrewulfe** [comment]
It was some sort of issue with making the same context current in multiple threads. It was handled properly when the surface was destroyed. But if it wasn't destroyed, restoring the context would fail, causing a new one to be created that wasn't hooked properly with the framebuffer renderer.

So I took the easy way out and just trashed the surface onPause().

(This doesn't fix rotation black screening.)

**Comment by a1studmuffin** [comment]
Awesome work, you found that quick! I just tested on my end and the lock/unlock issue is definitely resolved, sweet. I'm happy to accept the PR unless you have anything else you wanted to go in?

**Comment by Dyrewulfe** [comment]
Well, I found one last thing doing extended tests. This is still much better, but the rotation issue really needs resolved at some point. Starting the game from potrait with orientation set to landscape(or vice versa) creates, of course, black screen from rotating. On my device, this resolves itself with any pause/resume cycle. Same on your end?(you reported different behavior)

If it is, then this is at least a functional fix, and rotation can wait for now, imho.

**Comment by a1studmuffin** [comment]
Yep I agree. I saw the same as you, a black screen from rotation can be resolved by locking/unlocking the device, but only if the orientation was the same as initial startup orientation. I'll accept the PR as this is a definite improvement and we can continue work on the rotation issue. Thanks again for your help! :)

**Comment by Dyrewulfe** [comment]
> Thanks again for your help!

No problem, I was happy to do it. I was helping myself as well, really. The software renderer is just plain faster right now, makes for a better gameplay experience. Would likely have gotten this figured out sooner, but working purely on a mobile device has some drawbacks when it comes to workflow.

**Pull request merged**
